apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
commonLabels:
  version: v2
patchesStrategicMerge:
- ./e-capstone-patch.yml

images:
- name: eslam2017/e-capstone
  newTag: dev-50e686d
