apiVersion: v1
kind: Service
metadata:
  name:  e-capstone
  annotations:
    # service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "NAME=e-capstone-IMAGE_TAG"
spec:
  selector:
    app: e-capstone
  type: LoadBalancer
  ports:
  - name:  e-capstone
    port:  80
    targetPort: e-capstone
  # - name:  e-capstone-https
  #   port:  443
  #   targetPort: e-capstone

# e-capstone Deployment.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-capstone
  labels:
    app: e-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-capstone
  template:
    metadata:
      name: e-capstone
      labels:
        app: e-capstone   
    spec:      
      containers:
      - name: e-capstone
        image: eslam2017/e-capstone:IMAGE_TAG
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m        
        ports:
        - name: e-capstone
          containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Add Horizontal Pod Autoscaler object
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: e-capstone
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: e-capstone
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80