version: 2.1
executors:
  docker:
    docker:
      - image: docker
  python:
    docker:
      - image: python:3.7.3-stretch
  aws:
    docker:
      - image: amazon/aws-cli

jobs:
  lint:
    executor: python
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install --no-cache-dir Flask==1.1.2
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            hadolint Dockerfile

  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASS}
          docker build -t eslam2017/e-capstone:${CIRCLE_WORKFLOW_ID:0:7} .
          docker push eslam2017/e-capstone:${CIRCLE_WORKFLOW_ID:0:7}


workflows:
  e-capstone:
    jobs:
      - lint
      - build:
          requires:
            - "lint"