apiVersion: v1
kind: Service
metadata:
  labels:
    version: v1
  name: e-capstone
spec:
  ports:
  - name: e-capstone
    port: 80
    targetPort: 8080
  selector:
    app: e-capstone
    version: v1
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: e-capstone
    version: v1
  name: e-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-capstone
      version: v1
  template:
    metadata:
      labels:
        app: e-capstone
        version: v1
      name: e-capstone
    spec:
      containers:
      - image: eslam2017/e-capstone:main-af60c09
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          tcpSocket:
            port: 8080
        name: e-capstone
        ports:
        - containerPort: 8080
          name: e-capstone
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    version: v1
  name: e-capstone
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: e-capstone
