name: build and push python app hostname docker image.
on:
  push:
    branches:
      - 'main'
jobs:
  e-capstone_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: git branch and commit hash
      #   id: tag
      #   run: |
      #     export GIT_BRANCH=${GITHUB_REF#refs/heads/}
      #     export GITHUB_SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")
      #     echo ::set-output name=IMAGE_TAG::${GIT_BRANCH}-${GITHUB_SHA_SHORT}
      #     # echo ::set-output name=IMAGE_TAG::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: eslam2017/e-capstone
        # flavor: |
        #   latest=auto   
          tags: |
            type=ref,event=tag
            # dynamically set the branch name as a prefix
            type=sha,prefix={{branch}}-
            # dynamically set the branch name and sha as a custom tag
            type=raw,value={{branch}}-{{sha}}

      - name: Login to DockerHub
        id: docker_login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_UN }}
          password: ${{ secrets.DOCKER_HUB_PW }}

      - name: Build and push with latest tag      
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
            # eslam2017/e-capstone:latest
            # eslam2017/e-capstone:${{ steps.tag.outputs.IMAGE_TAG }}
            # eslam2017/e-capstone:${{ steps.meta.outputs.tags }}