name: build and push python app hostname docker image.
on:
  push:
    branches:
      - 'main'
jobs:
  e-capstone_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: git branch and commit hash
        run: |
          export git_branch=${GITHUB_REF#refs/heads/}
          export git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo $git_hash
          echo $git_branch
          echo ::set-output name=docker_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_UN }}
          password: ${{ secrets.DOCKER_HUB_PW }}
      - name: Build and push with latest tag      
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tag: ${{ steps.vars.outputs.docker_tag }}
          push: true
          tags: 
            # eslam2017/e-capstone:latest
            eslam2017/e-capstone:${tag}