name: build and push python app hostname docker image.
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: git branch and commit hash
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        # git_branch=${GITHUB_REF#refs/heads/}
        # run: |
          # echo $git_hash
          # echo git_branch

      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_UN }}
      #     password: ${{ secrets.DOCKER_HUB_PW }}
      # -
      #   name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: eslam2017/e-capstone:latest